import { ActivityType, AuditAction, NotificationType, TaskPriority, TaskType, UserRole } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { BusinessRuleError, ForbiddenError, NotFoundError } from "@/lib/errors";
import type { SessionUser } from "@/lib/auth/session";
import type { AdvanceStageInput } from "@/lib/validators/pipeline";
import {
  canAdvanceWithoutSkip,
  getLabelFor,
  getStageByKey,
  isLostStage,
  isTerminalStage,
  type StageKey,
} from "@/lib/constants";
import { writeAudit } from "@/server/services/audit";
import { notifyUser } from "@/server/services/notifications";

type Ctx = { actor: SessionUser; ip?: string; userAgent?: string };

async function followUpTitle(stageKey: StageKey, clientName: string): Promise<string> {
  const stage = await getStageByKey(stageKey);
  const label = stage?.label ?? stageKey;
  if (stage?.kind === "WON") return `Send thank-you and schedule service reminder for ${clientName}`;
  if (stage?.kind === "LOST") return `Re-engagement plan for ${clientName}`;
  switch (stageKey) {
    case "CONTACTED":
      return `Nurture ${clientName} — share curated selection`;
    case "ENGAGED":
      return `Schedule appointment with ${clientName}`;
    case "APPOINTMENT":
      return `Confirm appointment logistics with ${clientName}`;
    case "NEGOTIATION":
      return `Follow up on proposal with ${clientName}`;
    default:
      return `Follow up with ${clientName} — ${label}`;
  }
}

export async function advanceStage(clientId: string, input: AdvanceStageInput, ctx: Ctx) {
  const client = await prisma.client.findFirst({
    where: { id: clientId, deletedAt: null },
    select: { id: true, name: true, stage: true, ownerId: true },
  });
  if (!client) throw new NotFoundError("Client not found");
  if (ctx.actor.role === UserRole.ASSOCIATE && client.ownerId !== ctx.actor.id) {
    throw new ForbiddenError("You do not have access to this client");
  }
  if (client.stage === input.stage) {
    throw new BusinessRuleError("Client is already in this stage");
  }

  const targetStage = await getStageByKey(input.stage);
  if (!targetStage || !targetStage.active) {
    throw new BusinessRuleError(`Unknown or inactive stage: ${input.stage}`);
  }

  if ((await isTerminalStage(client.stage)) && ctx.actor.role !== UserRole.MANAGER) {
    throw new BusinessRuleError("Only managers may move a client out of a terminal stage");
  }

  const isManagerOverride = ctx.actor.role === UserRole.MANAGER && Boolean(input.force);
  if (!isManagerOverride && !(await canAdvanceWithoutSkip(client.stage, input.stage))) {
    if (ctx.actor.role !== UserRole.MANAGER) {
      throw new BusinessRuleError(
        `Illegal transition ${client.stage} → ${input.stage}. Stages cannot be skipped.`,
      );
    }
  }

  const [fromLabel, toLabel, toTerminal, toLost] = await Promise.all([
    getLabelFor(client.stage),
    getLabelFor(input.stage),
    isTerminalStage(input.stage),
    isLostStage(input.stage),
  ]);

  return prisma.$transaction(async (tx) => {
    const updated = await tx.client.update({
      where: { id: clientId },
      data: { stage: input.stage },
    });
    await tx.pipelineState.create({
      data: {
        clientId,
        stage: input.stage,
        fromStage: client.stage,
        note: input.note,
        changedById: ctx.actor.id,
      },
    });
    await tx.activity.create({
      data: {
        type: ActivityType.STAGE_CHANGE,
        clientId,
        actorId: ctx.actor.id,
        summary: `Stage ${fromLabel} → ${toLabel}`,
        body: input.note,
      },
    });

    // Auto follow-up: every non-terminal transition + explicit LOST gets a task.
    if (!toTerminal || toLost) {
      const due = new Date();
      due.setDate(due.getDate() + (toLost ? 14 : 2));
      await tx.task.create({
        data: {
          title: await followUpTitle(input.stage, client.name),
          description: `Auto-generated from stage change to ${toLabel}`,
          type: TaskType.FOLLOW_UP,
          priority: input.stage === "NEGOTIATION" ? TaskPriority.HIGH : TaskPriority.NORMAL,
          dueDate: due,
          clientId,
          assigneeId: client.ownerId,
          createdById: ctx.actor.id,
          autoGenerated: true,
          sourceJob: "pipeline_stage_change",
        },
      });
    }

    await writeAudit(
      {
        actorId: ctx.actor.id,
        action: AuditAction.STAGE_CHANGE,
        entityType: "client",
        entityId: clientId,
        before: { stage: client.stage },
        after: { stage: input.stage },
        metadata: { note: input.note, override: isManagerOverride },
        ip: ctx.ip,
        userAgent: ctx.userAgent,
      },
      tx,
    );

    if (ctx.actor.id !== client.ownerId) {
      await notifyUser(
        {
          userId: client.ownerId,
          type: NotificationType.STAGE_CHANGE,
          title: `Pipeline update — ${client.name}`,
          body: `${fromLabel} → ${toLabel}`,
          link: `/clients/${clientId}`,
        },
        tx,
      );
    }

    return updated;
  });
}

export async function listStageHistory(clientId: string) {
  return prisma.pipelineState.findMany({
    where: { clientId },
    orderBy: { createdAt: "desc" },
    include: { changedBy: { select: { id: true, name: true } } },
  });
}
