import { ActivityType, AuditAction, PipelineStage, Prisma, TaskPriority, TaskType, UserRole } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { BusinessRuleError, ForbiddenError, NotFoundError } from "@/lib/errors";
import type { SessionUser } from "@/lib/auth/session";
import type { CreateSaleInput } from "@/lib/validators/sale";
import { SERVICE_YEARS } from "@/lib/constants";
import { writeAudit } from "@/server/services/audit";

type Ctx = { actor: SessionUser; ip?: string; userAgent?: string };

export async function recordSale(input: CreateSaleInput, ctx: Ctx) {
  const client = await prisma.client.findFirst({
    where: { id: input.clientId, deletedAt: null },
    select: { id: true, ownerId: true, name: true, stage: true },
  });
  if (!client) throw new NotFoundError("Client not found");

  const associateId = input.associateId ?? client.ownerId;
  if (ctx.actor.role === UserRole.ASSOCIATE) {
    if (client.ownerId !== ctx.actor.id) throw new ForbiddenError("You do not have access to this client");
    if (associateId !== ctx.actor.id) throw new ForbiddenError("Associates may only attribute sales to themselves");
  }
  const associate = await prisma.user.findFirst({
    where: { id: associateId, active: true, deletedAt: null },
    select: { id: true, name: true },
  });
  if (!associate) throw new BusinessRuleError("Attributed associate does not exist or is inactive");

  const purchaseDate = new Date(input.purchaseDate);
  if (Number.isNaN(purchaseDate.getTime())) throw new BusinessRuleError("Invalid purchase date");

  return prisma.$transaction(async (tx) => {
    const sale = await tx.sale.create({
      data: {
        clientId: input.clientId,
        associateId,
        product: input.product,
        reference: input.reference,
        amount: new Prisma.Decimal(input.amount),
        currency: input.currency,
        purchaseDate,
        metadata: input.metadata ? (input.metadata as Prisma.InputJsonValue) : undefined,
      },
    });

    if (client.stage !== PipelineStage.WON) {
      await tx.client.update({ where: { id: client.id }, data: { stage: PipelineStage.WON } });
      await tx.pipelineState.create({
        data: {
          clientId: client.id,
          stage: PipelineStage.WON,
          fromStage: client.stage,
          note: `Sale recorded: ${input.product}`,
          changedById: ctx.actor.id,
        },
      });
    }

    await tx.activity.create({
      data: {
        type: ActivityType.SYSTEM,
        clientId: client.id,
        actorId: ctx.actor.id,
        summary: `Sale recorded — ${input.product}`,
        body: `Attributed to ${associate.name}`,
        metadata: { saleId: sale.id, amount: input.amount, currency: input.currency },
      },
    });

    const serviceDue = new Date(purchaseDate);
    serviceDue.setFullYear(serviceDue.getFullYear() + SERVICE_YEARS);
    await tx.task.create({
      data: {
        title: `Service reminder — ${client.name}`,
        description: `5-year service check for ${input.product}`,
        type: TaskType.SERVICE,
        priority: TaskPriority.NORMAL,
        dueDate: serviceDue,
        clientId: client.id,
        assigneeId: associateId,
        createdById: ctx.actor.id,
        autoGenerated: true,
        sourceJob: "sale_service_followup",
      },
    });

    await writeAudit(
      {
        actorId: ctx.actor.id,
        action: AuditAction.CREATE,
        entityType: "sale",
        entityId: sale.id,
        after: sale,
        ip: ctx.ip,
        userAgent: ctx.userAgent,
      },
      tx,
    );

    return sale;
  });
}

export async function listSalesForClient(clientId: string) {
  return prisma.sale.findMany({
    where: { clientId, deletedAt: null },
    orderBy: { purchaseDate: "desc" },
    include: { associate: { select: { id: true, name: true } } },
  });
}
