-- ─────────────────────────────────────────────────────────────
-- Master migration — consolidated init + journey configuration.
-- Creates the full Luxe CRM schema in a single step and seeds
-- the default journey stages/steps so pipeline data is usable
-- on day one.
-- ─────────────────────────────────────────────────────────────

-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `passwordHash` VARCHAR(191) NOT NULL,
    `role` ENUM('MANAGER', 'ASSOCIATE') NOT NULL DEFAULT 'ASSOCIATE',
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    INDEX `users_role_idx`(`role`),
    INDEX `users_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `clients` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NULL,
    `tier` ENUM('STANDARD', 'PRIORITY', 'VIP') NOT NULL DEFAULT 'STANDARD',
    `stage` VARCHAR(64) NOT NULL DEFAULT 'PROSPECT',
    `ownerId` VARCHAR(191) NOT NULL,
    `birthday` DATE NULL,
    `anniversary` DATE NULL,
    `notes` TEXT NULL,
    `wishlist` JSON NULL,
    `collection` JSON NULL,
    `lastContactAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `clients_name_idx`(`name`),
    INDEX `clients_phone_idx`(`phone`),
    INDEX `clients_ownerId_idx`(`ownerId`),
    INDEX `clients_stage_idx`(`stage`),
    INDEX `clients_tier_idx`(`tier`),
    INDEX `clients_deletedAt_idx`(`deletedAt`),
    INDEX `clients_lastContactAt_idx`(`lastContactAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `activities` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('NOTE', 'MESSAGE', 'CALL', 'APPOINTMENT', 'STAGE_CHANGE', 'SYSTEM') NOT NULL,
    `clientId` VARCHAR(191) NOT NULL,
    `actorId` VARCHAR(191) NOT NULL,
    `summary` VARCHAR(500) NOT NULL,
    `body` TEXT NULL,
    `metadata` JSON NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `deletedAt` DATETIME(3) NULL,

    INDEX `activities_clientId_occurredAt_idx`(`clientId`, `occurredAt`),
    INDEX `activities_actorId_occurredAt_idx`(`actorId`, `occurredAt`),
    INDEX `activities_type_idx`(`type`),
    INDEX `activities_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tasks` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(300) NOT NULL,
    `description` TEXT NULL,
    `type` ENUM('MESSAGE', 'CALL', 'APPOINTMENT', 'FOLLOW_UP', 'SERVICE') NOT NULL,
    `status` ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    `priority` ENUM('LOW', 'NORMAL', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'NORMAL',
    `dueDate` DATETIME(3) NOT NULL,
    `completedAt` DATETIME(3) NULL,
    `clientId` VARCHAR(191) NOT NULL,
    `assigneeId` VARCHAR(191) NOT NULL,
    `createdById` VARCHAR(191) NOT NULL,
    `autoGenerated` BOOLEAN NOT NULL DEFAULT false,
    `sourceJob` VARCHAR(64) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `tasks_dueDate_status_idx`(`dueDate`, `status`),
    INDEX `tasks_assigneeId_status_idx`(`assigneeId`, `status`),
    INDEX `tasks_clientId_idx`(`clientId`),
    INDEX `tasks_type_idx`(`type`),
    INDEX `tasks_priority_idx`(`priority`),
    INDEX `tasks_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `sales` (
    `id` VARCHAR(191) NOT NULL,
    `clientId` VARCHAR(191) NOT NULL,
    `associateId` VARCHAR(191) NOT NULL,
    `product` VARCHAR(300) NOT NULL,
    `reference` VARCHAR(128) NULL,
    `amount` DECIMAL(14, 2) NOT NULL,
    `currency` CHAR(3) NOT NULL DEFAULT 'USD',
    `purchaseDate` DATETIME(3) NOT NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `sales_associateId_purchaseDate_idx`(`associateId`, `purchaseDate`),
    INDEX `sales_clientId_idx`(`clientId`),
    INDEX `sales_purchaseDate_idx`(`purchaseDate`),
    INDEX `sales_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pipeline_states` (
    `id` VARCHAR(191) NOT NULL,
    `clientId` VARCHAR(191) NOT NULL,
    `stage` VARCHAR(64) NOT NULL,
    `fromStage` VARCHAR(64) NULL,
    `note` TEXT NOT NULL,
    `changedById` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `pipeline_states_stage_idx`(`stage`),
    INDEX `pipeline_states_clientId_createdAt_idx`(`clientId`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `templates` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `category` VARCHAR(80) NOT NULL,
    `body` TEXT NOT NULL,
    `variables` JSON NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `templates_category_idx`(`category`),
    INDEX `templates_active_idx`(`active`),
    INDEX `templates_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `audit_logs` (
    `id` VARCHAR(191) NOT NULL,
    `actorId` VARCHAR(191) NOT NULL,
    `action` ENUM('CREATE', 'UPDATE', 'DELETE', 'ASSIGN', 'STAGE_CHANGE', 'LOGIN', 'LOGOUT') NOT NULL,
    `entityType` VARCHAR(64) NOT NULL,
    `entityId` VARCHAR(64) NOT NULL,
    `before` JSON NULL,
    `after` JSON NULL,
    `metadata` JSON NULL,
    `ip` VARCHAR(64) NULL,
    `userAgent` VARCHAR(300) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `audit_logs_actorId_createdAt_idx`(`actorId`, `createdAt`),
    INDEX `audit_logs_entityType_entityId_idx`(`entityType`, `entityId`),
    INDEX `audit_logs_action_idx`(`action`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `notifications` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `type` ENUM('SLA_BREACH', 'TASK_OVERDUE', 'TASK_ASSIGNED', 'CLIENT_ASSIGNED', 'STAGE_CHANGE', 'SYSTEM') NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `body` TEXT NOT NULL,
    `link` VARCHAR(500) NULL,
    `readAt` DATETIME(3) NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `notifications_userId_readAt_idx`(`userId`, `readAt`),
    INDEX `notifications_type_idx`(`type`),
    INDEX `notifications_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: journey_stages
CREATE TABLE `journey_stages` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(64) NOT NULL,
    `label` VARCHAR(80) NOT NULL,
    `order` INTEGER NOT NULL,
    `kind` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    `stagnationDays` INTEGER NOT NULL DEFAULT 5,
    `slaHours` INTEGER NOT NULL DEFAULT 24,
    `color` VARCHAR(16) NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `journey_stages_key_key`(`key`),
    INDEX `journey_stages_order_idx`(`order`),
    INDEX `journey_stages_active_idx`(`active`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: journey_steps
CREATE TABLE `journey_steps` (
    `id` VARCHAR(191) NOT NULL,
    `stageId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `description` VARCHAR(500) NULL,
    `order` INTEGER NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `journey_steps_stageId_order_idx`(`stageId`, `order`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `clients` ADD CONSTRAINT `clients_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `activities` ADD CONSTRAINT `activities_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `clients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `activities` ADD CONSTRAINT `activities_actorId_fkey` FOREIGN KEY (`actorId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `clients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_assigneeId_fkey` FOREIGN KEY (`assigneeId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tasks` ADD CONSTRAINT `tasks_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales` ADD CONSTRAINT `sales_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `clients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sales` ADD CONSTRAINT `sales_associateId_fkey` FOREIGN KEY (`associateId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pipeline_states` ADD CONSTRAINT `pipeline_states_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `clients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `pipeline_states` ADD CONSTRAINT `pipeline_states_changedById_fkey` FOREIGN KEY (`changedById`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_actorId_fkey` FOREIGN KEY (`actorId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `notifications` ADD CONSTRAINT `notifications_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `journey_steps` ADD CONSTRAINT `journey_steps_stageId_fkey`
    FOREIGN KEY (`stageId`) REFERENCES `journey_stages`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- ─────────────────────────── Seed default journey stages ───────────────────────────

INSERT INTO `journey_stages` (`id`, `key`, `label`, `order`, `kind`, `stagnationDays`, `slaHours`, `active`, `createdAt`, `updatedAt`) VALUES
    ('seed_stage_prospect',     'PROSPECT',     'Prospect',     1, 'ACTIVE', 3,  24, true, NOW(3), NOW(3)),
    ('seed_stage_contacted',    'CONTACTED',    'Contacted',    2, 'ACTIVE', 5,  24, true, NOW(3), NOW(3)),
    ('seed_stage_engaged',      'ENGAGED',      'Engaged',      3, 'ACTIVE', 7,  48, true, NOW(3), NOW(3)),
    ('seed_stage_appointment',  'APPOINTMENT',  'Appointment',  4, 'ACTIVE', 3,  24, true, NOW(3), NOW(3)),
    ('seed_stage_negotiation',  'NEGOTIATION',  'Negotiation',  5, 'ACTIVE', 5,  24, true, NOW(3), NOW(3)),
    ('seed_stage_won',          'WON',          'Won',          6, 'WON',    9999, 9999, true, NOW(3), NOW(3)),
    ('seed_stage_lost',         'LOST',         'Lost',         7, 'LOST',   9999, 9999, true, NOW(3), NOW(3));

-- ─────────────────────────── Seed default journey steps ───────────────────────────

INSERT INTO `journey_steps` (`id`, `stageId`, `title`, `description`, `order`, `active`, `createdAt`, `updatedAt`) VALUES
    ('seed_step_prospect_1',    'seed_stage_prospect',    'Reach out within 24h',      'Open the relationship fast', 1, true, NOW(3), NOW(3)),
    ('seed_step_prospect_2',    'seed_stage_prospect',    'Capture wishlist',          'Tastes, gifts, grail pieces', 2, true, NOW(3), NOW(3)),

    ('seed_step_contacted_1',   'seed_stage_contacted',   'Book a discovery call',     'Confirm intent, not just interest', 1, true, NOW(3), NOW(3)),
    ('seed_step_contacted_2',   'seed_stage_contacted',   'Share curated pieces',      'Three max — edit hard', 2, true, NOW(3), NOW(3)),

    ('seed_step_engaged_1',     'seed_stage_engaged',     'Schedule in-boutique visit', 'Private room if VIP', 1, true, NOW(3), NOW(3)),
    ('seed_step_engaged_2',     'seed_stage_engaged',     'Send catalog',              'Reference for follow-up', 2, true, NOW(3), NOW(3)),

    ('seed_step_appointment_1', 'seed_stage_appointment', 'Confirm reservation',        NULL, 1, true, NOW(3), NOW(3)),
    ('seed_step_appointment_2', 'seed_stage_appointment', 'Prepare stock selection',    'Pull pieces day-before', 2, true, NOW(3), NOW(3)),

    ('seed_step_negotiation_1', 'seed_stage_negotiation', 'Finalize price',             NULL, 1, true, NOW(3), NOW(3)),
    ('seed_step_negotiation_2', 'seed_stage_negotiation', 'Confirm delivery date',      NULL, 2, true, NOW(3), NOW(3)),

    ('seed_step_won_1',         'seed_stage_won',         'Schedule aftercare touchpoint', 'First check-in at 30 days', 1, true, NOW(3), NOW(3));
